name: Deploy new version to demo.abantecart.com
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Chekout
        uses: actions/checkout@v3

      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & publish to dockerhub
        run: |
          cd $GITHUB_WORKSPACE/docker
          docker login --username=${{ secrets.DOCKERHUB_USER }} --password-stdin <<<${{ secrets.DOCKERHUB_PASSWORD }}
          docker buildx build --platform linux/amd64,linux/arm64 -t abantecart/abantecart_demo:latest --push ./
